### ISSUE TITLE
incompatibility with Apple Mac mini m1 core

### ISSUE THREAD

**Issue by keinanp** [gardner-lab/video-capture#24]
Firstly, I have checked, and the triggering/video acquisition works well for an intel core mac. However, when I try it on a Mac Mini with an M1 core that is intended to be the acquisition machine, the VideoCapture App opens, recognizes both the video and audio from the CMOS, but cannot recognize the Arduino and thus cannot perform the triggering for the LED. I assume back when you were working on this project M1 cores weren’t out yet, but am wondering if you may know how to fix the problem. I tried to rebuild the project for the M1 machine, and it fails, due to many errors, some syntactical in the code and some I don’t understand. I have also tried to use rosetta, but the option is not possible for the video capture app as it is for other applications.
 
In a bit more detail, when running the app on the M1 core: 
The app seems to recognize the port of the Arduino, as shown in the screenshot, however, when I click this, the toggle jumps back to “Arduino” and I cannot toggle the LED bar..
Under the exact same configurations, the app worked fine on the Intel Core.

![Unknown](https://github.com/gardner-lab/video-capture/assets/94174310/7d5a41f1-cc76-4943-a8b7-9fb55aab91d7)

**Comment by WALIII** [comment]
Its not on the roadmap to update the software for apple silicon, but if you implement a solution we'll merge it!
